server.port=8009
spring.application.name=stok
server.servlet.context-path=/api/stok

security.jwt.expiration=3600
security.jwt.secret=6df1df81-833f-41cc-920b-23d062953e43

security.user.login=stockroot
security.user.salt=PszAC1XoHSKwBxG4
security.user.pwd=Root@123

spring.datasource.driver=cdata.jdbc.postgresql.PostgreSQLDriver
spring.datasource.url=jdbc:postgresql://localhost:5432/stok
spring.datasource.username=postgres
spring.datasource.schema=public
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.flyway.table=SCHEMA_VERSION
spring.flyway.locations=classpath:sql
spring.flyway.enabled=true

excel.invoice.file-path=classpath:templates/template_facture.xlsx
excel.bl.file-path=classpath:templates/template_bl.xlsx
