ALTER TABLE INVOICE ADD REFERENCE_INVOICE BIGINT;
ALTER TABLE INVOICE ADD REFERENCE_BL BIGINT;

CREATE INDEX IDX_REFERENCE_INVOICE_REF ON INVOICE (REFERENCE_INVOICE);
CREATE INDEX IDX_REFERENCE_BL_REF ON INVOICE (REFERENCE_BL);
