CREATE TABLE USER_DETAIL (
    ID SERIAL PRIMARY KEY,
    PUBLIC_ID UUID NOT NULL,
    LOGIN VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(64)
);


CREATE INDEX IDX_USER_ID ON USER_DETAIL (ID);
CREATE INDEX IDX_LOGIN ON USER_DETAIL (LOGIN);
