CREATE TABLE WORK_STATION (
    ID SERIAL PRIMARY KEY,
    PUBLIC_ID UUID NOT NULL,
    MACHINE VARCHAR(256),
    OPERATOR VARCHAR(64),
    DATE TIMESTAMP,
    DURATION INT
);

CREATE INDEX IDX_WORK_STATION_ID ON WORK_STATION (ID);

CREATE TABLE STATION_TRANSFORMATION (
    ID SERIAL PRIMARY KEY,
    PUBLIC_ID UUID NOT NULL,
    TYPE VARCHAR(8),
    QUANTITY REAL
);

CREATE INDEX IDX_STATION_TRANS_ID ON STATION_TRANSFORMATION (ID);
CREATE INDEX IDX_STATION_TRANS_TYPE ON STATION_TRANSFORMATION (TYPE);

