CREATE TABLE ACTION (
    ID SERIAL PRIMARY KEY,
    PUBLIC_ID UUID NOT NULL,
    ACTION_PUBLIC_ID UUID,
    TYPE VARCHAR(32),
    DATE_TIME TIMESTAMP,
    DESCRIPTION VARCHAR(256),
    OPERATOR VARCHAR(64)
);

CREATE INDEX IDX_ACTION_ID ON ACTION (ID);