CREATE TABLE CLIENT (
    ID SERIAL PRIMARY KEY,
    PUBLIC_ID UUID NOT NULL,
    NAME VARCHAR(256),
    EMAIL VARCHAR(256),
    ADDRESS VARCHAR(256),
    REFERENCE VARCHAR(32),
    CREATION_DATE TIMESTAMP,
    CREATION_STATUS VARCHAR(16)
);

CREATE INDEX IDX_CLIENT_ID ON CLIENT (ID);
CREATE INDEX IDX_CLIENT_NAME ON CLIENT (NAME);
