CREATE TABLE INVOICE (
    ID SERIAL PRIMARY KEY,
    PUBLIC_ID UUID NOT NULL,
    REFERENCE VARCHAR(32),
    CREATION_DATE TIMESTAMP,
    CREATION_STATUS VARCHAR(16),
    TOTAL_BRUT NUMERIC(11,3),
    TOTAL_TVA NUMERIC(11,3),
    TIMBER REAL,
    TOTAL_NET NUMERIC(11,3),
    PRICE_AS_TEXT VARCHAR(255)
);

CREATE INDEX IDX_INVOICE_ID ON INVOICE (ID);
CREATE INDEX IDX_INVOICE_REFERENCE ON INVOICE (REFERENCE);
CREATE INDEX IDX_PRODUCT_PUBLIC_ID ON PRODUCT (PUBLIC_ID);
