CREATE TABLE PRODUCT_INVOICE (
    ID SERIAL PRIMARY KEY,
    PUBLIC_ID UUID NOT NULL,
    PRODUCT_PUBLIC_ID UUID,
    PRODUCT_NAME VARCHAR(256),
    QUANTITY NUMERIC(11,3),
    UNIT_PRICE NUMERIC(11,3),
    DISCOUNT REAL,
    TOTAL_PRICE NUMERIC(11,3),
    TVA REAL
);

CREATE INDEX IDX_P_INVOICE_ID ON PRODUCT_INVOICE (ID);
CREATE INDEX IDX_P_INVOICE_PRO_PUB_ID ON PRODUCT_INVOICE (PRODUCT_PUBLIC_ID);
