version: '3.8'

services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_DB: stok
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stok_network

  stok_api:
    image: stok_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:8009"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/stok
    depends_on:
      - postgres
    networks:
      - stok_network

volumes:
  postgres_data:

networks:
  stok_network:
    driver: bridge
