spring.datasource.driver=cdata.jdbc.postgresql.PostgreSQLDriver
spring.datasource.url=jdbc:postgresql://localhost:5432/stok
spring.datasource.username=postgres
spring.datasource.schema=public
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.flyway.table=SCHEMA_VERSION
spring.flyway.locations=classpath:sql
spring.flyway.enabled=true

excel.invoice.file-path=classpath:templates/template_facture.xlsx
excel.bl.file-path=classpath:templates/template_bl.xlsx
